language: objective-c
osx_image: xcode8.1
xcode_workspace: helloworld-ios-app.xcworkspace
xcode_scheme: helloworld-ios-app
xcode_sdk: iphonesimulator

before_install:
  - travis_wait pod repo update --silent

notifications:
  irc: "irc.freenode.org#feedhenry"

script:
  - xcodebuild clean build -workspace helloworld-ios-app.xcworkspace -scheme helloworld-ios-app -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6' GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

branches:
  only:
    - master
